server:
  port: 9786

spring:
  application:
    name: llm-avalon
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1
      connection-init-sql: set names utf8mb4
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:./fluxion;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=mysql;
  jpa:
    hibernate:
      ddl-auto: none
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: false  # 日志中显示sql语句
    properties:
      hibernate:
        enable_lazy_load_no_trans: true # 解决懒加载问题 no Session
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  h2:
    # h2嵌入式数据库控制台，可以通过浏览器访问 ip:port/h2-console
    # file 模式 用户名密码都是空
    # mem 模式 用户名 sa 密码空
    console:
      path: /h2-console
      enabled: true


# log
logging:
  config: classpath:log4j2.xml
